### ISSUE TITLE
DDL 및 더미데이터 쿼리 작성

### ISSUE THREAD

**Issue by LeeHanEum** [kgu-developers/aics-server#118]
### Describe

데이터베이스 스키마를 생성하는 CREATE DDL문과 더미데이터 INSERT 쿼리를 작성합니다.

### Tasks

- [x] `resource/db` 디렉토리 하위에 `schema.sql` `data.sql` 파일 생성
- [x] `schema.sql` 파일에 CREATE 문 작성 (JPA가 자동 생성 해주는 쿼리와 동일한지 확인)
- [x] `data.sql` 파일에 INSERT 쿼리 작성

### ETC

1. 더미데이터는 예시 데이터를 보여주기 위한 목적이므로 각 테이블마다 2~5개 정도만 작성합니다.
2. 더미데이터는 애플리케이션 실행 시 자동 삽입하지 않을 예정입니다. (application.yml 설정 불필요)
3. 추후 스키마 구조가 변경 될 경우 더미데이터 수정에 대한 이슈 생성 후 작업 진행해주세요
