### ISSUE TITLE
Jacoco를 사용한 테스트 커버리지 측정

### ISSUE THREAD

**Issue by LeeHanEum** [kgu-developers/aics-server#126]
### Describe

Jacoco 라이브러리를 활용하여 프로젝트의 테스트 코드 커버리지를 측정합니다. 
최소 커버리지 기준을 설정하여 테스트 품질을 향상시키는 것이 해당 작업의 목적이에요. 
설정된 기준에 미달하는 경우, Pull Request가 병합되지 않도록 Github Actions를 활용하여 CI 파이프라인에 제약을 추가합니다.

### Tasks

- [x] Jacoco 의존성 추가
- [x] 커버리지 측정 결과를 PR 코멘트로 업로드
- [x] 커버리지가 80% 미만일 때 PR 병합 되지 않도록 제약 추가
- [x] Report를 html, xml 형태로 `/build/jacoco` 디렉토리에 추가

### ETC

1. 기준 커버리지는 우선 80%로 설정하고, 추후 운영 과정에서 조정할 예정입니다.
2. 해당 워크플로는 develop 브랜치를 대상으로 하는 Pull Request가 열렸을 때 동작하도록 구현합니다
