### ISSUE TITLE
전공 생성 API 구현

### ISSUE THREAD

**Issue by LeeHanEum** [kgu-developers/aics-server#16]
### Describe

Major 전공 생성 API를 구현합니다.

### Tasks

- [x] `MajorController` 구현 - `"/api/v1/major"` 엔드포인트로 Post 요청을 처리
- [x] `MajorService` 구현 - 필요에 따라 중복 확인 로직 등 추가
- [x] `MajorRepository` 구현 - save jpa 메서드 호출
- [x] `MajorExceptionCode`를 사용하여 적절한 예외 발생

### ETC

모듈 간 구조는 아래와 같습니다.
```
aics-api
├── major
│   ├── presentation
│   │   ├── MajorController
│   │   ├── request
│   │   │   └── majorRequest
│   │   ├── response
│   │   │   └── majorResponse
│   │   └── exception
│   │       └── MajorExceptionCode
│   │       └── NotFoundException
│   └── application
│       └── MajorService

aics-domain
├── major
│   ├── domain
│   │   ├── Major
│   │   └── MajorRepository
│   └── infrastructure
│       ├── JpaMajorRepository
│       └── MajorRepositoryImpl
```

[싱글 모듈 DDD 아키텍처로 진행한 프로젝트 참고](https://github.com/9oormthonUNIV-3th-KGU/family-note-server)
