### ISSUE TITLE
유저 회원가입 API 구현

### ISSUE THREAD

**Issue by LeeHanEum** [kgu-developers/aics-server#17]
### Describe

User 회원가입 api를 구현합니다.

### Tasks

- [x] `UserController` 구현 - `"/api/v1/user"` 엔드포인트로 Post 요청을 처리
- [x] `UserService` 구현 - 필요에 따라 중복 확인 로직 등 추가
- [x] `UserRepository` 구현 - save jpa 메서드 호출
- [x] `UserExceptionCode`를 사용하여 적절한 예외 발생
- [x] 비밀번호 암호화 처리

### ETC

모듈 간 구조는 아래와 같습니다.
```
aics-api
├── user
│   ├── presentation
│   │   ├── UserController
│   │   ├── request
│   │   │   └── UserRequest
│   │   ├── response
│   │   └── exception
│   │       └── UserExceptionCode
│   └── application
│       └── UserService

aics-domain
├── user
│   ├── domain
│   │   ├── User
│   │   └── UserRepository
│   └── infrastructure
│       ├── JpaUserRepository
│       └── UserRepositoryImpl
```

[싱글 모듈 DDD 아키텍처로 진행한 프로젝트 참고](https://github.com/9oormthonUNIV-3th-KGU/family-note-server)
