### ISSUE TITLE
회원 정보 조회 API 구현

### ISSUE THREAD

**Issue by LeeHanEum** [kgu-developers/aics-server#23]
### Describe

회원 정보 조회 API를 구현합니다.

### Tasks

- [x] User 엔티티에 `email`, `phone` 필드를 추가합니다. (기존 ERD에는 없었음)
- [x] 회원의 상세정보를 반환하는 `UserDetailsResponse` dto를 생성합니다.
- [x] GET `/api/v1/user` API를 만들고 Swagger에 응답 스키마 정보를 추가합니다.

### ETC

<img width="1027" alt="스크린샷 2024-10-21 오후 3 39 17" src="https://github.com/user-attachments/assets/0d9c81be-ab7d-4a06-9ef6-76b6cf2c3ef4"><br>

1. 가입한지 몇일 되었는지 명시하는 필드는 응답 스키마에서 일단 제외합니다.
2. 날짜와 연관된 필드는 모두 dto 레벨의 정적 팩토리 메서드에서 TimeStamp로 포맷팅하여 반환합니다.
3. NPE가 발생하지 않도록 주의해서 작업합니다.
4. ENUM 타입은 타입 그대로 반환합니다.
