### ISSUE TITLE
회원 엔티티 수정

### ISSUE THREAD

**Issue by LeeHanEum** [kgu-developers/aics-server#31]
### Describe

24.10.22 기획 회의에서 논의한 회원 정보만 남기고 나머지 모든 필드를 삭제하는 리팩토링을 진행 합니다.

### Tasks

- [x] 학번, 이름, 전화번호, 이메일, 비밀번호, 권한을 제외한 모든 필드 삭제
- [x] 학번을 PK로 수정 (personalId -> userId)
- [x] POST `/api/v1/majors` API 삭제 후 major를 enum으로 변경
- [x] role 필드를 `ROLE_USER`, `ROLE_ADMIN`, `ROLE_SUPER` 3가지 권한으로 분류

### ETC

회의록을 참고하여 작업 진행해주세요
