### ISSUE TITLE
회원 가입 API 수정

### ISSUE THREAD

**Issue by LeeHanEum** [kgu-developers/aics-server#32]
### Describe

24.10.22에서 논의한대로 회원가입 절차를 간소화 합니다.

<img width="652" alt="스크린샷 2024-10-23 오전 12 31 19" src="https://github.com/user-attachments/assets/e8079d6f-7ab8-4b59-91da-9dc7085b38f0">

### Tasks

- [x] 학번, 비밀번호, 이름, 이메일, 휴대폰 번호만 RequestBody로 받습니다.
- [x] 학번에 대한 중복 검사로직만 유지하고 나머지는 삭제 합니다. (다른 검증 메서드들도 삭제)
- [x] `major`는 enum 타입으로 받아 처리합니다. 
- [x] 이메일의 도메인이 `@kyonggi.ac.kr`인지 검증하는 로직을 추가합니다.
- [x] 비밀번호 유효성 검증 로직을 수정합니다. (영문, 숫자, 특수문자 조합 8~15 자리)

### ETC

회의록을 참고하여 작업 진행해주세요
