### ISSUE TITLE
파일 업로드 기능 구현

### ISSUE THREAD

**Issue by LeeHanEum** [kgu-developers/aics-server#34]
### Describe

게시판 첨부 파일 업로드에 사용할 업로드 서비스 로직을 구현합니다. 

### Tasks

- [x] `domain` 모듈에 `FileEntity` 및 `FileRepository`를 구현합니다.
- [x] util 혹은 handler 클래스는 `global-utils` 모듈에 구현합니다.
- [x] 업로드를 위해 로컬에 저장한 파일은 삭제하며 예외 발생 시 `log.error`로 로그를 남겨둡니다.
- [x] 파일 디렉토리 구조는 `/도메인/년/월/일`로 저장합니다. (ex. `/posts/24/10/23/`)

### ETC

서비스 전반에 영향을 미칠 중요한 로직이니 관련 레퍼런스 많이 찾아보고 작업 진행 부탁드려요
