### ISSUE TITLE
Post 엔티티 수정 및 글쓰기 API 구현

### ISSUE THREAD

**Issue by LeeHanEum** [kgu-developers/aics-server#36]
### Describe

24.10.22 기획 회의를 바탕으로 Post 엔티티를 수정합니다.
글쓰기 API를 구현합니다.

### Tasks

- [x] Post 엔티티의 content를 TEXT 타입으로 수정해주세요 (길이 제한 없애기 위함)
- [x] Post 엔티티의 category를 nullable 허용해주세요. (추후 category 추가 가능성을 고려)
- [x] POST `/api/v1/posts` 엔드포인트의 글쓰기 API를 구현해주세요.

### ETC

1. 글쓰기 API에서 첨부파일은 별도의 API로 분리할 예정이므로 고려하지 않으셔도 됩니다.
2. 노션의 회의록을 참고하여 구현해주세요.
