### ISSUE TITLE
게시글 상세 조회 API 구현

### ISSUE THREAD

**Issue by LeeHanEum** [kgu-developers/aics-server#43]
### Describe

<img width="755" alt="스크린샷 2024-10-28 오후 2 23 43" src="https://github.com/user-attachments/assets/56e3c980-95c2-4143-8f7b-393ae5bf6a2c"> <br>
게시글 상세 조회 API를 구현합니다.

### Tasks

- [x] `/api/v1/posts/{postId}` 엔드포인트로 매핑합니다.
- [x] 사진을 참고하여 `PostDetailResponse`를 구성하고 반환합니다.
- [x] `PostId` 기반으로 조회하며 `@PathVariable`로 식별자를 받습니다.

### ETC

학과 홈페이지를 참고하여 구현 해주세요!
