### ISSUE TITLE
게시글 고정 여부 토글 API 구현

### ISSUE THREAD

**Issue by LeeHanEum** [kgu-developers/aics-server#45]
### Describe
<img width="749" alt="스크린샷 2024-10-28 오후 2 40 16" src="https://github.com/user-attachments/assets/43a3b319-c0e9-4382-9a2f-3dfe88673a22"> <br>

게시글 고정 여부 토글 API를 구현합니다.

### Tasks

- [x] post 엔티티에 `isPinned`를 추가하여 고정 여부를 표시
- [x] PATCH `/api/v1/posts/{postId}/pin` API 구현
- [x] 고정 --> 고정 해제, 고정 해제 --> 고정 으로 토클 방식으로 동작
- [x] 페이징 처리 정렬 조건에 고정 여부를 포함하도록 수정

### ETC

DB에서 게시글을 조회할 때, is_pinned 컬럼을 기준으로 우선 정렬하도록 수정해야 합니다.
