### ISSUE TITLE
Spring 인터셉터를 적용한 로그 설정 추가

### ISSUE THREAD

**Issue by LeeHanEum** [kgu-developers/aics-server#7]
### Describe

Spring 인터셉터를 적용하여 API가 실행될 때 로그 정보가 출력되도록 합니다.

### Tasks

- [ ] API 실행 마다 로그 출력되도록 pointcut 설정
- [ ] 500 서버 에러에 대한 세부 로그 출력
- [ ] API 실행 시간 출력
