### ISSUE TITLE
교수 Professor 생성 / 수정 / 삭제 / 조회 API 구현

### ISSUE THREAD

**Issue by LeeHanEum** [kgu-developers/aics-server#73]
### Describe

교수 정보를 생성, 수정, 삭제, 조회하는 API를 구현합니다.

1. DELETE 매핑을 통한 교수 삭제: DELETE 요청을 사용하여 교수 정보를 즉시 삭제할 수 있도록 합니다.
2. 교수 목록 조회 : 조회 API는 교수 목록을 가나다 순으로 정렬하여 제공합니다.

### Tasks

- [x] POST `/api/v1/professor` - 교수 생성 API 구현
- [x] PATCH `/api/v1/professor/{id}` - 교수 수정 API 구현
- [x] DELETE `/api/v1/professor/{id}` - 교수 삭제 API 구현
- [x] GET `/api/v1/professor` - 교수 목록 조회 API 구현 (교수명 가나다 순 정렬)

### ETC

현재는 정렬 기준이 가나다 이지만, 교수 정렬 순서에 대한 고민은 다같이 해보면 좋을것 같습니다!
