### ISSUE TITLE
연구실 Lab 생성 / 수정 / 삭제 / 조회 API 구현

### ISSUE THREAD

**Issue by LeeHanEum** [kgu-developers/aics-server#74]
### Describe

연구실 정보를 생성, 수정, 삭제, 조회하는 API를 구현합니다.

DELETE 매핑을 통한 연구실 삭제: DELETE 요청을 사용하여 연구실 정보를 즉시 삭제할 수 있도록 합니다.
연구실 목록 조회 : 조회 API는 연구실 목록을 가나다 순으로 정렬하여 제공합니다.

### Tasks

- [x] POST `/api/v1/labs` - 연구실 생성 API 구현
- [x] PATCH `/api/v1/labs/{id}` - 연구실 수정 API 구현
- [x] DELETE `/api/v1/labs/{id}` - 연구실 삭제 API 구현
- [x] GET `/api/v1/labs` - 연구실 목록 조회 API 구현 (연구실명 가나다 순 정렬)
