### ISSUE TITLE
학과 소개 About 생성 / 수정 / 조회 API 구현

### ISSUE THREAD

**Issue by LeeHanEum** [kgu-developers/aics-server#77]
### Describe

`학과 소개` 및 `교육 활동`에 해당하는 페이지의 내용을 JSON으로 받아 Text롤 저장합니다.
<img width="1441" alt="스크린샷 2024-11-06 오전 11 16 48" src="https://github.com/user-attachments/assets/62577e84-693d-4b92-b8f8-5ef6216a84b6">

### Tasks

- [x] POST `/api/v1/abouts` - 소개 생성 API
- [x] GET `/api/v1/abouts?main={main}&sub={sub}&detail={detail}` - 카테고리별 조회 API
- [x] PATCH `/api/v1/abouts/{id}` - 소개 수정 API (본문 내용만 수정)

### ETC

1. 파일 업로드는 별도의 API로 분리할 예정이니 고려하지 않습니다.
2. 조회 시 detail은 필수 파라미터가 아닙니다
