### ISSUE TITLE
Post 게시글 엔티티 클래스 구현

### ISSUE THREAD

**Issue by LeeHanEum** [kgu-developers/aics-server#8]
### Describe

ERD에 명시된 Post 게시글 엔티티 클래스를 구현합니다.

### Tasks

- [x] `aics-domain` 모듈에 `post` 패키지를 추가하고 `Post` 엔티티 클래스를 구현
- [x] `category`는 `post` 패키지에 enum 클래스로 구현
- [x] `user` 엔티티와 매핑

### ETC

1. #4의 유의사항을 참고해서 구현해주세요.
2. `user` 엔티티 매핑 구현 시 , 매핑 전략을 명시해주세요
